import { NextRequest, NextResponse } from "next/server";
import { requireAuth } from "@/lib/auth";
import { getSupabaseAdmin } from "@/lib/supabase/admin";

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const userOrRes = await requireAuth();
  if (userOrRes instanceof NextResponse) return userOrRes;
  const user = userOrRes;
    const { id: forgeId } = await params;
    const { searchParams } = new URL(req.url);
    const sessionId = searchParams.get("sessionId");

    if (!sessionId) {
      return NextResponse.json({ error: "sessionId is required" }, { status: 400 });
    }

    const supabase = await getSupabaseAdmin();

    const { data: session } = await supabase
      .from("builder_sessions")
      .select("*")
      .eq("id", sessionId)
      .eq("forge_id", forgeId)
      .single();

    if (!session) {
      return NextResponse.json({ error: "Session not found" }, { status: 404 });
    }

    const { data: forge } = await supabase
      .from("forges")
      .select("name")
      .eq("id", forgeId)
      .single();

    const { data: artifacts } = await supabase
      .from("builder_artifacts")
      .select("path, content")
      .eq("session_id", sessionId)
      .order("path", { ascending: true });

    if (!artifacts || artifacts.length === 0) {
      return NextResponse.json({ error: "No artifacts to export" }, { status: 400 });
    }

    const slug = (forge?.name ?? "forge")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "");
    const folderName = `${slug}-generated`;

    const JSZip = (await import("jszip")).default;
    const zip = new JSZip();
    const folder = zip.folder(folderName)!;

    for (const artifact of artifacts) {
      folder.file(artifact.path, artifact.content);
    }

    const metadataContent = [
      `# Generated by MergeForge`,
      `Forge: ${forge?.name ?? "Unknown"}`,
      `Session ID: ${sessionId}`,
      `Generated: ${new Date().toISOString()}`,
      `Artifacts: ${artifacts.length} files`,
      `Prompt: ${session.prompt}`,
    ].join("\n");
    folder.file("MERGEFORGE.md", metadataContent);

    const buffer = await zip.generateAsync({
      type: "nodebuffer",
      compression: "DEFLATE",
      compressionOptions: { level: 6 },
    });

    return new Response(buffer, {
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${folderName}.zip"`,
        "Content-Length": String(buffer.length),
      },
    });
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
