import { NextRequest, NextResponse } from "next/server";
import { requireAuth } from "@/lib/auth";
import { getSupabaseAdmin } from "@/lib/supabase/admin";
import { getOctokit } from "@/lib/github";

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const userOrRes = await requireAuth();
  if (userOrRes instanceof NextResponse) return userOrRes;
  const user = userOrRes;
    const { id: forgeId } = await params;
    const body = await req.json();
    const { sessionId, repoName, isPrivate = true, description } = body;

    if (!sessionId || !repoName) {
      return NextResponse.json({ error: "sessionId and repoName are required" }, { status: 400 });
    }

    if (!/^[a-zA-Z0-9_. -]{1,100}$/.test(repoName)) {
      return NextResponse.json({ error: "Invalid repoName: use letters, numbers, dots, hyphens, underscores only" }, { status: 400 });
    }

    const supabase = await getSupabaseAdmin();

    const { data: session } = await supabase
      .from("builder_sessions")
      .select("id, forge_id")
      .eq("id", sessionId)
      .eq("forge_id", forgeId)
      .single();

    if (!session) {
      return NextResponse.json({ error: "Session not found" }, { status: 404 });
    }

    const { data: ghAccount } = await supabase
      .from("github_accounts")
      .select("access_token")
      .eq("user_id", user.id)
      .single();

    if (!ghAccount?.access_token) {
      return NextResponse.json({ error: "GitHub account not linked" }, { status: 400 });
    }

    const { data: artifacts } = await supabase
      .from("builder_artifacts")
      .select("path, content")
      .eq("session_id", sessionId);

    if (!artifacts || artifacts.length === 0) {
      return NextResponse.json({ error: "No artifacts to push" }, { status: 400 });
    }

    const { data: job } = await supabase
      .from("deploy_jobs")
      .insert({ session_id: sessionId, forge_id: forgeId, created_by: user.id, target: "github", status: "running" })
      .select()
      .single();

    try {
      const octokit = getOctokit(ghAccount.access_token);

      await octokit.rest.repos.createForAuthenticatedUser({
        name: repoName,
        description: description || "Generated by MergeForge",
        private: isPrivate,
        auto_init: true,
      });

      const { data: ghUser } = await octokit.rest.users.getAuthenticated();
      const owner = ghUser.login;

      let branch = "heads/main";
      let refData;
      try {
        refData = await octokit.rest.git.getRef({ owner, repo: repoName, ref: "heads/main" });
      } catch {
        branch = "heads/master";
        refData = await octokit.rest.git.getRef({ owner, repo: repoName, ref: "heads/master" });
      }

      const baseCommitSha = refData.object.sha;
      const { data: commitData } = await octokit.rest.git.getCommit({
        owner, repo: repoName, commit_sha: baseCommitSha,
      });
      const baseTreeSha = commitData.tree.sha;

      const treeItems = [];
      for (const artifact of artifacts) {
        const { data: blob } = await octokit.rest.git.createBlob({
          owner, repo: repoName, content: artifact.content, encoding: "utf-8",
        });
        treeItems.push({ path: artifact.path, mode: "100644" as const, type: "blob" as const, sha: blob.sha });
      }

      const { data: newTree } = await octokit.rest.git.createTree({
        owner, repo: repoName, base_tree: baseTreeSha, tree: treeItems,
      });

      const { data: newCommit } = await octokit.rest.git.createCommit({
        owner, repo: repoName,
        message: "Initial commit — generated by MergeForge",
        tree: newTree.sha,
        parents: [baseCommitSha],
      });

      await octokit.rest.git.updateRef({
        owner, repo: repoName, ref: branch, sha: newCommit.sha,
      });

      const repoUrl = `https://github.com/${owner}/${repoName}`;

      await supabase
        .from("deploy_jobs")
        .update({ status: "completed", github_repo_url: repoUrl })
        .eq("id", job.id);

      return NextResponse.json({ success: true, repoUrl, deployJobId: job.id });
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "GitHub push failed";
      await supabase.from("deploy_jobs").update({ status: "failed", error_message: msg }).eq("id", job.id);
      return NextResponse.json({ error: msg }, { status: 500 });
    }
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
