import { SupabaseClient } from '@supabase/supabase-js';
import { getOctokit } from '@/lib/github';
import { AgentSSEEvent } from '@/lib/types';

export async function runDeployAgent(params: {
  runId: string;
  forgeId: string;
  sessionId: string;
  repoName: string;
  projectName: string;
  isPrivate: boolean;
  supabase: SupabaseClient;
  onEvent: (event: AgentSSEEvent) => void;
}): Promise<{ repoUrl: string | null; deployUrl: string | null; fileCount: number }> {
  const { runId, forgeId, sessionId, repoName, projectName, isPrivate, supabase, onEvent } = params;

  const { data: run } = await supabase.from('agent_runs').select('created_by').eq('id', runId).single();
  if (!run) throw new Error('Run not found');

  const { data: ghAccount } = await supabase
    .from('github_accounts')
    .select('access_token')
    .eq('user_id', run.created_by)
    .single();

  const { data: files } = await supabase
    .from('agent_files')
    .select('*')
    .eq('run_id', runId)
    .in('status', ['done', 'fixed', 'lint_fixed', 'test_written'])
    .in('file_type', ['source', 'config', 'schema', 'env', 'readme'])
    .or(`path.like.%__tests__%,path.not.like.%__tests__%`);

  const validFiles = (files ?? []).filter((f: any) => {
    if (f.status === 'error') return false;
    if (f.path.includes('__tests__') && f.file_type === 'test') return true;
    if (f.file_type !== 'test') return true;
    return false;
  });

  if (validFiles.length === 0) throw new Error('No completed files to deploy');

  onEvent({ type: 'deploy_start', agent: 'deploy', message: `Deploy agent starting — ${validFiles.length} files to push` });
  await supabase.from('agent_runs').update({ current_agent: 'deploy' }).eq('id', runId);

  const octokit = getOctokit(ghAccount?.access_token);

  onEvent({ type: 'progress', agent: 'deploy', message: `Creating GitHub repository: ${repoName}` });

  const user = await octokit.rest.users.getAuthenticated();
  const owner = user.data.login;

  try {
    await octokit.rest.repos.createForAuthenticatedUser({
      name: repoName,
      description: `Built by MergeForge AI agents`,
      private: isPrivate,
      auto_init: true,
    });
  } catch (err: any) {
    if (err.status !== 422) throw err;
  }

  const refData = await octokit.rest.git.getRef({ owner, repo: repoName, ref: 'heads/main' }).catch(() =>
    octokit.rest.git.getRef({ owner, repo: repoName, ref: 'heads/master' })
  );
  const baseCommitSha = refData.data.object.sha;

  const commitData: any = await octokit.rest.git.getCommit({ owner, repo: repoName, commit_sha: baseCommitSha });
  const baseTreeSha = commitData.data.tree.sha;

  const BATCH = 10;
  const chunks: typeof validFiles[] = [];
  for (let i = 0; i < validFiles.length; i += BATCH) chunks.push(validFiles.slice(i, i + BATCH));

  const treeItems: any[] = [];
  for (const chunk of chunks) {
    const blobs = await Promise.all(chunk.map(f =>
      octokit.rest.git.createBlob({ owner, repo: repoName, content: f.content, encoding: 'utf-8' }).then(r => ({ sha: r.data.sha, path: f.path }))
    ));
    treeItems.push(...blobs.map(b => ({ path: b.path, mode: '100644', type: 'blob', sha: b.sha })));
  }

  const newTree = await octokit.rest.git.createTree({
    owner, repo: repoName, base_tree: baseTreeSha, tree: treeItems,
  });

  const newCommit = await octokit.rest.git.createCommit({
    owner, repo: repoName,
    message: `Initial commit — ${validFiles.length} files generated by MergeForge AI (${new Date().toISOString().split('T')[0]})`,
    tree: newTree.data.sha,
    parents: [baseCommitSha],
  });

  await octokit.rest.git.updateRef({ owner, repo: repoName, ref: 'heads/main', sha: newCommit.data.sha });

  const repoUrl = `https://github.com/${owner}/${repoName}`;
  onEvent({ type: 'progress', agent: 'deploy', message: `Pushed ${validFiles.length} files to ${repoUrl}` });

  let deployUrl: string | null = null;
  const vercelToken = process.env.VERCEL_API_KEY;

  if (vercelToken) {
    onEvent({ type: 'progress', agent: 'deploy', message: `Deploying to Vercel: ${projectName}` });
    const teamQuery = process.env.VERCEL_TEAM_ID ? `?teamId=${process.env.VERCEL_TEAM_ID}` : '';

    const vercelRes = await fetch(`https://api.vercel.com/v13/deployments${teamQuery}`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${vercelToken}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name: projectName,
        framework: 'nextjs',
        target: 'production',
        files: validFiles.map((f: any) => ({ file: f.path, data: f.content, encoding: 'utf-8' })),
      }),
    });

    if (vercelRes.ok) {
      const dep = await vercelRes.json();
      deployUrl = `https://${dep.url}`;
      onEvent({ type: 'deploy_done', agent: 'deploy', message: `Deployed: ${deployUrl}`, metadata: { url: deployUrl } });
    }
  } else {
    onEvent({ type: 'progress', agent: 'deploy', message: 'Skipping Vercel — VERCEL_API_TOKEN not set. Repo is on GitHub.' });
  }

  await supabase.from('deploy_jobs').insert({
    session_id: sessionId,
    forge_id: forgeId,
    created_by: run.created_by,
    target: 'github',
    status: 'completed',
    github_repo_url: repoUrl,
    vercel_deploy_url: deployUrl,
  });

  return { repoUrl, deployUrl, fileCount: validFiles.length };
}
