Deno.serve(async (req) => {
  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), {
      status: 405,
      headers: { "Content-Type": "application/json" },
    });
  }

  try {
    const { forgeId, sessionId, prompt, targetStack, plan } = await req.json();

    if (!sessionId || !plan) {
      return new Response(JSON.stringify({ error: "sessionId and plan required" }), {
        status: 400,
        headers: { "Content-Type": "application/json" },
      });
    }

    const openaiKey = Deno.env.get("OPENAI_API_KEY");
    const groqKey = Deno.env.get("GROQ_API_KEY");

    async function generateArtifact(
      filePath: string,
      fileDescription: string,
      planContext: unknown,
      apiKey: string,
      provider: "openai" | "groq"
    ): Promise<string> {
      const systemPrompt = `You are an expert full-stack developer. Generate production-ready code for the file described. Output ONLY the raw file content — no markdown, no code fences, no explanation.`;

      const userPrompt = `File: {filePath}\nPurpose: {fileDescription}\nApp context:\n{JSON.stringify(planContext, null, 2)}`;

      const model = provider === "openai"
        ? "gpt-4o-mini"
        : "llama-3.1-8b-instant";

      const baseUrl = provider === "openai"
        ? "https://api.openai.com/v1/chat/completions"
        : "https://api.groq.com/openai/v1/chat/completions";

      const res = await fetch(baseUrl, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer {apiKey}`,
        },
        body: JSON.stringify({
          model,
          max_tokens: 1500,
          temperature: 0.2,
          messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: userPrompt },
          ],
        }),
      });

      if (!res.ok) throw new Error(`{provider} error: {res.status}`);
      const data = await res.json();
      return data.choices?.[0]?.message?.content ?? "";
    }

    function slugify(path: string): string {
      return path.replace(/\/+/g, "_").replace(/[^a-zA-Z0-9_]/g, "_");
    }

    function buildFallbackArtifacts(planData: unknown): Array<{ path: string; content: string; artifact_type: string }> {
      const p = planData as {
        summary?: string;
        pages?: Array<{ path: string; title: string }>;
        routes?: Array<{ path: string; method: string }>;
        schema?: Array<{ table: string; columns: string[] }>;
        env_vars?: string[];
      };
      const artifacts: Array<{ path: string; content: string; artifact_type: string }> = [];

      // README.md
      artifacts.push({
        path: "README.md",
        content: `# Generated App\n\n{p.summary ?? "Generated by MergeForge"}\n\n## Pages\n{(p.pages ?? []).map((pg: { path: string; title: string }) => `- {pg.path} — {pg.title}`).join("\n")}\n\n## API Routes\n{(p.routes ?? []).map((r: { path: string; method: string }) => `- {r.method} {r.path}`).join("\n")}\n\n## Database Schema\n{(p.schema ?? []).map((t: { table: string; columns: string[] }) => `### {t.table}\n{t.columns.join("\n")}`).join("\n\n")}\n\n## Environment Variables\n{(p.env_vars ?? []).map((v: string) => `{v}=`).join("\n")}\n\n## Getting Started\n1. Install dependencies: \`npm install\`\n2. Set up environment variables (see .env.example)\n3. Run database migrations\n4. Start dev server: \`npm run dev\``,
        artifact_type: "readme",
      });

      // .env.example
      artifacts.push({
        path: ".env.example",
        content: (p.env_vars ?? ["NEXT_PUBLIC_SUPABASE_URL", "NEXT_PUBLIC_SUPABASE_ANON_KEY", "SUPABASE_SERVICE_ROLE_KEY"]).map((v: string) => `{v}=`).join("\n"),
        artifact_type: "env",
      });

      // package.json
      artifacts.push({
        path: "package.json",
        content: JSON.stringify({
          name: "generated-mergeforge-app",
          version: "0.1.0",
          private: true,
          scripts: {
            dev: "next dev --turbopack",
            build: "next build",
            start: "next start",
          },
          dependencies: {
            next: "15.1.7",
            react: "19.0.0",
            "react-dom": "19.0.0",
            "@supabase/supabase-js": "^2.50.0",
          },
        }, null, 2),
        artifact_type: "code",
      });

      // app/layout.tsx
      artifacts.push({
        path: "app/layout.tsx",
        content: `import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Generated App",
  description: "Built with MergeForge",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <nav className="p-4 border-b">MergeForge App</nav>
        <main className="p-8">{children}</main>
      </body>
    </html>
  );
}
`,
        artifact_type: "code",
      });

      // app/page.tsx
      artifacts.push({
        path: "app/page.tsx",
        content: `export default function Home() {
  return (
    <div className="min-h-screen">
      <section className="py-20 text-center">
        <h1 className="text-4xl font-bold mb-4">{p.summary ?? "Welcome"}</h1>
        <p className="text-muted-foreground">Built with MergeForge</p>
      </section>
    </div>
  );
}
`,
        artifact_type: "code",
      });

      // API routes
      for (const route of (p.routes ?? []).slice(0, 4)) {
        const safeName = slugify(route.path);
        artifacts.push({
          path: `app/api/{safeName}/route.ts`,
          content: `import { NextRequest, NextResponse } from "next/server";

export async function {route.method}(req: NextRequest) {
  return NextResponse.json({ ok: true, path: "{route.path}" });
}
`,
          artifact_type: "code",
        });
      }

      // Database migration
      if (p.schema && p.schema.length > 0) {
        const createTables = p.schema.map((t: { table: string; columns: string[] }) =>
          `CREATE TABLE IF NOT EXISTS {t.table} (\n  {t.columns.map(c => c).join(",\n  ")}\n);`
        ).join("\n\n");
        artifacts.push({
          path: "supabase/migrations/001_init.sql",
          content: createTables,
          artifact_type: "schema",
        });
      }

      return artifacts;
    }

    const hasAI = !!(openaiKey || groqKey);
    let artifacts: Array<{ path: string; content: string; artifact_type: string }> = [];

    if (hasAI) {
      const ctx = { prompt, targetStack, plan };
      const key = openaiKey ? openaiKey : groqKey!;
      const provider = openaiKey ? "openai" : "groq";

      // Build list of files to generate
      const fileList: Array<{ path: string; description: string }> = [
        { path: "README.md", description: "App README with setup instructions" },
        { path: ".env.example", description: "Environment variable template" },
        { path: "package.json", description: "npm package configuration for Next.js 15 + React 19 app" },
        { path: "app/layout.tsx", description: "Root Next.js layout with html/body/nav" },
        { path: "app/page.tsx", description: "Home page component" },
      ];

      // Add API routes
      for (const route of (plan.routes ?? []).slice(0, 4)) {
        const safeName = slugify(route.path);
        fileList.push({
          path: `app/api/{safeName}/route.ts`,
          description: `{route.method} {route.path} API route handler`,
        });
      }

      // Add schema migration
      if (plan.schema?.length > 0) {
        fileList.push({
          path: "supabase/migrations/001_init.sql",
          description: "PostgreSQL CREATE TABLE statements for all schema tables",
        });
      }

      // Add pages (up to 3 non-root)
      for (const page of (plan.pages ?? []).filter((p: { path: string }) => p.path !== "/").slice(0, 3)) {
        const pagePath = page.path.replace(/^\//, "");
        fileList.push({
          path: `app/{pagePath}/page.tsx`,
          description: `Next.js page: {page.title} — {page.purpose}`,
        });
      }

      // Generate sequentially to avoid rate limits
      for (const file of fileList) {
        try {
          const content = await generateArtifact(file.path, file.description, ctx, key, provider);
          artifacts.push({ path: file.path, content, artifact_type: "code" });
        } catch (err) {
          console.error(`Failed to generate {file.path}:`, err);
        }
      }
    }

    // Always include fallback artifacts if AI not available or as supplement
    if (!hasAI || artifacts.length === 0) {
      const fallback = buildFallbackArtifacts(plan);
      // Merge, avoiding duplicates by path
      const existingPaths = new Set(artifacts.map(a => a.path));
      for (const f of fallback) {
        if (!existingPaths.has(f.path)) {
          artifacts.push(f);
        }
      }
    }

    return new Response(JSON.stringify({ artifacts }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  } catch (err) {
    console.error("generate-app-artifacts error:", err);
    return new Response(JSON.stringify({ error: String(err) }), {
      status: 500,
      headers: { "Content-Type": "application/json" },
    });
  }
});
